/**
 * REST API client — typed with the generated OpenAPI types (ADR-001).
 *
 * Import `apiClient` and use it for all REST calls.
 * Types come from `../generated/api` (auto-generated by `npm run generate-api:file`).
 *
 * Example:
 *   const { data, error } = await apiClient.GET("/health");
 *
 * The baseUrl uses a relative path so the Vite dev proxy forwards requests
 * to the backend (see vite.config.ts). In production the frontend is served
 * from the same origin as the backend.
 */

import createClient from "openapi-fetch";

import type { paths } from "../generated/api";

export const apiClient = createClient<paths>({
  baseUrl: "/",
});
